version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresCont
    environment:
      POSTGRES_USER: tofutest
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: partdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
