version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgresCont
    environment:
      POSTGRES_USER: tofutest
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: partdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=tofutest
      - DB_PASSWORD=1234
      - DB_NAME=partdata
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  services:
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
